# Generated by Django 4.2.1 on 2023-05-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('another_contact', models.CharField(blank=True, max_length=100)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.PositiveIntegerField(blank=True)),
                ('illnesses', models.TextField(blank=True)),
                ('massage_type', models.CharField(max_length=100)),
                ('therapy_duration', models.PositiveIntegerField(blank=True, default=1)),
                ('one_visit_price', models.PositiveIntegerField(blank=True, null=True)),
                ('visit_days', models.CharField(max_length=100)),
                ('visit_time', models.TimeField()),
                ('more_info', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
    ]
