# Generated by Django 4.2.1 on 2023-06-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='visit_date',
            field=models.DateField(null=True),
        ),
    ]
