# Generated by Django 4.2.1 on 2023-06-10 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='ClientVisiter',
        ),
    ]
