# Generated by Django 4.2.1 on 2023-06-10 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients_data', '0003_client_alter_visit_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientVisiter',
        ),
    ]
