# Generated by Django 4.2.1 on 2023-06-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_data', '0004_delete_clientvisiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='sex',
            field=models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], max_length=1),
        ),
    ]
