# Generated by Django 4.2.1 on 2023-06-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_data', '0005_alter_client_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='balance',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='done_and_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
