# Generated by Django 4.2.1 on 2023-07-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_data', '0006_client_balance_visit_done_and_paid_alter_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='prepayment',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
