# Generated by Django 4.2.1 on 2023-07-02 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients_data', '0007_visit_prepayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='done_and_paid',
            new_name='completed',
        ),
    ]
