# Generated by Django 4.2.1 on 2023-07-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_data', '0008_rename_done_and_paid_visit_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visit_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
