# Generated by Django 4.2.1 on 2023-07-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_data', '0010_alter_visit_massage_type_alter_visit_visit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='debt',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
