# Generated by Django 4.2.1 on 2023-07-25 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients_data', '0013_alter_client_debt_alter_client_deposit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payments',
            new_name='Payment',
        ),
    ]
