# Generated by Django 4.2.1 on 2023-07-28 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients_data', '0014_rename_payments_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['payment_date']},
        ),
        migrations.RemoveField(
            model_name='client',
            name='debt',
        ),
    ]
