# Generated by Django 4.2.1 on 2023-07-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_data_per_visit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='completed',
            new_name='done_and_paid',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='prepayment',
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_price',
            field=models.PositiveIntegerField(),
        ),
    ]
