# Generated by Django 4.2.1 on 2023-07-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_data_per_visit', '0002_rename_completed_visit_done_and_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='massage_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
